# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclang
    - CONFIG=osx_c_compilertoolchain_c

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "6B5lZSpnzx8LA9cSW7hXTASwmQ+ha2haUacd1Wyr0nqiC/iE5K25Pi4gJwjPzh7bCLDOIUyTcuRQTFIB2Gg6pTPmNhVE5RmrZb+4IfHpjOwV9KtXczINgELLLhAhFt04c17dJJqGAzLbNp/DDJJ5Srzo1+pEpwXJIV7jv3VfREAJ95jcVigdoFX0sQqnQflz9WpOnwySuXNf7Hn8TH0baJW5k7+usy56v1VEShJU32slMgVx/tBqg3LBnQJpmN6JedCBYDq6liyORBshG0pejI/xcgyVdk2JJ9blFlkAEkiOm2s+I1xhFpLd9OY6L/MDjLPUDQuQIJmb7912wG8ypxo38Mw8wXV9gf45GHLo6h/TPhgXAM7oDPh1kFzaIzT3ojOqYTIH4frsmr10v8LiiWqxRNrHEax8+geoZbFFmkInmA+uzZNGz8SM3xP9RePBPD1lYL3DYBl4/aru6bm+Ndw8pb+TPyHobV5Jcs2PYN/OYyMq+2LVxELgEOWTUrTeLqnyuBLzY5VpjD3+D2gX7/4/6ho+XLVxaRDIZP2lXVGx8nPxiyIon/BQbW5AQinjZraQp8iFN/MC+AICm5XwWQ30Tfh4R51GGQoFbENk3IUVSXU70UW91JrzFrMiZTIXmijOnyqXioIE+yaenaNcHGziO9HHYCtv8LQfDaKRhyM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml